### ISSUE TITLE
Downloaded dmg and double clicking on MacOS sequoia but nothing happens

### ISSUE THREAD

**Issue by dinbtechit** [inndevs/mac-taskbar-public#14]
Downloaded - `Mac.Taskbar.0.12.dmg` 

![image](https://github.com/user-attachments/assets/faa56ecb-38eb-44be-8bcb-7b55de683039)

**Comment by schneidermayer** [comment]
see this guide on how to install:

https://github.com/inndevs/mac-taskbar-public/issues/5#issuecomment-1976843334
