### ISSUE TITLE
Crashes when right-clicked to access Settings

### ISSUE THREAD

**Issue by tiredbro** [inndevs/mac-taskbar-public#2]
And after crashing, the app won't restart. Had to reinstall.

**Comment by schneidermayer** [comment]
Ah yeah, settings dialog is what I am working right now ... I will provide the first settings in the next release .. will take osme days - stay tuned

**Comment by schneidermayer** [comment]
the crash is fixed. the dialog is still empty, but i am already testing the first settings on my machine.
