### ISSUE TITLE
Nothing happens when clicking .dmg

### ISSUE THREAD

**Issue by hbread00** [inndevs/mac-taskbar-public#5]
Device: Macbook pro m2 pro Samona 14.0 23A344
Downloaded the dmg file, try double-clicked to launch, right-clicked to launch and drag in the App file both nothing happen.

**Comment by schneidermayer** [comment]
Which macOs version are you using?
When you launch the app, is there a permission popup in the background?
We can also look on discord if you cannot get it to work. Otherwise I will release a 14.0 version in a few days.

**Comment by hbread00** [comment]
Samona 14.0 23A344
No permission popup
Tried to search for "task" "bar" "taskbar" in Activity Monitor, no process was found.

**Comment by hbread00** [comment]
> Which macOs version are you using? When you launch the app, is there a permission popup in the background? We can also look on discord if you cannot get it to work. Otherwise I will release a 14.0 version in a few days.

Samona 14.0 23A344
No permission popup.
Tried to search for "task" "bar" "taskbar" in Activity Monitor, no process was found.

**Comment by ilcavero** [comment]
same thing happened to me but I noticed the dmg was indeed mounted in finder and could click there to install, what seems to be missing is the autoplay

**Comment by schneidermayer** [comment]
@hbread00  it the solution from @ilcavero help you?

**Comment by hbread00** [comment]
@schneidermayer

**Comment by hbread00** [comment]
> @hbread00 it the solution from @ilcavero help you?

@schneidermayer no, nothing happens when clicking in finder

**Comment by hbread00** [comment]
@schneidermayer workable!
The finder does not show other disks by default. Need to manually turn on the display in the finder settings to show the mounted image from step 2.

**Comment by schneidermayer** [comment]
Happy to hear it worked for you.

If you have any more feature requests or bugs, please let me know, as I still want to improve the Mac Taskbar (whilst als not bloating it).

**Comment by KevinGhadyani-Okta** [comment]
For other folks, my Finder had Locations hidden:
![image](https://github.com/inndevs/mac-taskbar-public/assets/97464104/6d87d55a-1e9e-497d-a594-0b807b0334a9)

You have to hover over "locations" and click the drop-down chevron to get them to show:
![image](https://github.com/inndevs/mac-taskbar-public/assets/97464104/b095c80d-d57c-4061-9075-29de0aa7ade2)
